version: '3.8'
services:
  scrollfolio:
    image: nginx:alpine
    container_name: scrollfolio
    ports:
      - "80:80"
    volumes:
      - ./:/usr/share/nginx/html/:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s